86bwvpxgv/creating pages for root and auth
LaGoGa/game-admin pull request #2
Opened 2023-12-28 18:12 UTC by piotrgorski23

2023-12-28 22:48 UTC, chrisganov requested changes

2023-12-28 22:48 UTC, chrisganov commented on src/router.tsx
> +  path: "authPage",
are you sure that this is correct? The path would represent the url path, hence in this case it would look like "/authPage". Isn't there a better route naming?

2023-12-29 23:18 UTC, piotrgorski23 commented on src/router.tsx
> +  path: "authPage",
I have changed it to /authentication. Is it good now?

2024-01-03 06:39 UTC, chrisganov approved these changes

2024-01-03 06:39 UTC, merged